# Copyright (c) 2020, 2021, 2022 Humanitarian OpenStreetMap Team
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

version: "3"

volumes:
  fmtm_db_data:
  central_db_data:

networks:
  fmtm-dev:

services:
  fmtm-db:
    image: postgis/postgis:14-3.3-alpine
    container_name: fmtm_db
    volumes:
      - fmtm_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - fmtm-dev
    restart: unless-stopped

  api:
    build:
      context: src/backend
      # target: debug
    container_name: fmtm_api
    volumes:
      - ./src/backend:/app/backend
      # - ../odkconvert/odkconvert:/home/appuser/.local/lib/python3.9/site-packages/odkconvert
    depends_on:
      - fmtm-db
      - central
    env_file:
      - .env
    environment:
      - DB_URL=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@fmtm-db:5432/${DB_NAME}
    ports:
      - "8000:8000"
    networks:
      - fmtm-dev
    restart: unless-stopped

  ui:
    build:
      context: src/frontend
      target: debug
    container_name: fmtm_ui
    volumes:
       - ./src/frontend/main:/app
       - /app/node_modules/
    ports:
      - "8080:8080"
    networks:
      - fmtm-dev
    restart: unless-stopped

  central-db:
    image: postgis/postgis:14-3.3-alpine
    container_name: central_db
    volumes:
      - central_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=odk
      - POSTGRES_PASSWORD=odk
      - POSTGRES_DB=odk
    networks:
      - fmtm-dev
    restart: unless-stopped

  central:
    build:
      context: .
      dockerfile: central.dockerfile
    container_name: central_api
    depends_on:
      - central-db
      - pyxform
    command: [ "./wait-for-it.sh", "central-db:5432", "--", "./start-odk.sh" ]
    ports:
      - "8383:8383"
    networks:
      - fmtm-dev
    restart: unless-stopped

  pyxform:
    image: 'ghcr.io/getodk/pyxform-http:v1.10.1.1'
    networks:
      - fmtm-dev
    restart: always

