version: '3'

services:

  main:
    depends_on:
      - openlayers
    build:
         context: ./main
         dockerfile: Dockerfile
    image: main:latest
    ports:
      - '8080:80'

    restart: always

    networks:
      - fmtm-network

  openlayers:
    build:
         context: ./fmtm_openlayer_map
         dockerfile: Dockerfile
    image: openlayers:latest
    ports:
      - '8081:80'
    restart: always

    networks:
      - fmtm-network


networks:
  fmtm-network:
    driver: bridge
