name: Deploy FMTM

on:
  # Trigger on image build complete
  workflow_run:
    workflows: ["Build Container Images"]
    types:
      - completed
  # Allow manual trigger
  workflow_dispatch:

jobs:
  deploy-containers:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Environment to .env
        run: echo "${{ secrets.DOTENV }}" > .env

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable Host key verification
        # Hack to prevent "Host key verification failed". Should be replaced with a ssh-keyscan based solution
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy
        run: docker compose --file docker-compose.deploy.yml up --detach --pull
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
