name: PR

on:
  pull_request:
    branches:
      - main
      - staging
      - development
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: PyTest
        uses: ./.github/workflows/reusable/pytest.yml

      - name: Frontend Tests
        uses: ./.github/workflows/reusable/frontend_test.yml
