name: Production Deploy

on:
  # Push includes PRs
  push:
    branches:
      - main
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:
  # Trigger on image build
  workflow_run:
    workflows: ["Build Container Image in GHCR"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Environment to .env
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: echo "${{ secrets.DOTENV }}" > .env

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.FMTM_HOTOSM_ORG_PRIV_KEY }}

      - name: Disable Host key verification
        # Hack to prevent "Host key verification failed". Should be replaced with a ssh-keyscan based solution
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy
        run: docker compose --file docker-compose.deploy.yml up --detach --pull
        env:
          DOCKER_HOST: "ssh://svcfmtm@fmtm.hotosm.org"
